// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen2MZ","status":false,"description":"[Ver1.5.0]Yet another menu screen layout","parameters":{"allowWindowDisp":"true","maxColsMenu":"5","commandRows":"2","commandCols":"4","isDisplayStatus":"true","doesDisplayNextLevel":"false","textNextLevel":"Next%1","statusStyle":"standard","display map name":"true","location string":"Location:","bgBitmapMenu":"","doesNotSetItemScene":"true","bgBitmapItem":"","doesNotSetSkillScene":"true","bgBitmapSkill":"","doesNotSetEquipScene":"true","bgBitmapEquip":"","doesNotSetStatusScene":"true","bgBitmapStatus":"","doesNotSetOptionScene":"true","bgBitmapOptions":"","doesNotSetSaveScene":"true","bgBitmapFile":"","doesNotSetEndScene":"true","bgBitmapGameEnd":"","doesNotSetShopScene":"false","bgBitmapShop":"","doesNotSetNameScene":"true","bgBitmapNameInput":"","bgUserDefined":""}},
{"name":"ChangeSelectItemWindowMZ","status":false,"description":"Change the various settings of item selecting window.","parameters":{"Switch ID":"1","Max Columns":"1","Visible Rows":"8","X position":"-1","Y position":"-1","Width":"-1"}},
{"name":"wasdKeyMZ","status":true,"description":"It is a plugin that corresponds to the wasd move.","parameters":{}},
{"name":"SVActorPositionMZ","status":false,"description":"[Ver1.1.5]Change actors' position on screen at sideview battle.","parameters":{"actor1 Xpos":"550","actor1 Ypos":"240","actor2 Xpos":"550 + 32 + 32","actor2 Ypos":"240 + 48","actor3 Xpos":"550 + 32 * 2","actor3 Ypos":"240 + 48 * 2","actor4 Xpos":"550 + 32 * 3 + 32","actor4 Ypos":"240 + 48 * 3"}},
{"name":"SimplePassiveSkillMZ","status":false,"description":"[1.1.0]Make passive skill that change parameters and set traits.","parameters":{}}
];
